(function(){var f=this,h=function(a){var b=typeof a;if("object"==b)if(a){if(a instanceof Array)return"array";if(a instanceof Object)return b;var d=Object.prototype.toString.call(a);if("[object Window]"==d)return"object";if("[object Array]"==d||"number"==typeof a.length&&"undefined"!=typeof a.splice&&"undefined"!=typeof a.propertyIsEnumerable&&!a.propertyIsEnumerable("splice"))return"array";if("[object Function]"==d||"undefined"!=typeof a.call&&"undefined"!=typeof a.propertyIsEnumerable&&!a.propertyIsEnumerable("call"))return"function"}else return"null";
else if("function"==b&&"undefined"==typeof a.call)return"object";return b};var k=parseFloat("0.06"),l=isNaN(k)||1<k||0>k?0:k;var n=function(a){n[" "](a);return a};n[" "]=function(){};var p=function(a,b){for(var d in a)Object.prototype.hasOwnProperty.call(a,d)&&b.call(null,a[d],d,a)};var q;r:{var r=f.navigator;if(r){var s=r.userAgent;if(s){q=s;break r}}q=""};var t=-1!=q.indexOf("Opera")||-1!=q.indexOf("OPR"),v=-1!=q.indexOf("Trident")||-1!=q.indexOf("MSIE"),w=-1!=q.indexOf("Gecko")&&-1==q.toLowerCase().indexOf("webkit")&&!(-1!=q.indexOf("Trident")||-1!=q.indexOf("MSIE")),x=-1!=q.toLowerCase().indexOf("webkit");
(function(){var a="",b;if(t&&f.opera)return a=f.opera.version,"function"==h(a)?a():a;w?b=/rv\:([^\);]+)(\)|;)/:v?b=/\b(?:MSIE|rv)[: ]([^\);]+)(\)|;)/:x&&(b=/WebKit\/(\S+)/);b&&(a=(a=b.exec(q))?a[1]:"");return v&&(b=(b=f.document)?b.documentMode:void 0,b>parseFloat(a))?String(b):a})();var y=function(a){this.b=[];this.a={};for(var b=0,d=arguments.length;b<d;++b)this.a[arguments[b]]=""},A=function(){var a=z,b="317150500 317150501 317150502 317150503 317150504 317150505".split(" ");if(a.a.hasOwnProperty(1)&&""==a.a[1]){r:{if(!(1E-4>Math.random())){var d=Math.random();if(d<l){try{var c=new Uint16Array(1);window.crypto.getRandomValues(c);d=c[0]/65536}catch(e){d=Math.random()}b=b[Math.floor(d*b.length)];break r}}b=null}b&&""!=b&&a.a.hasOwnProperty(1)&&(a.a[1]=b)}};
y.prototype.c=function(a){return this.a.hasOwnProperty(a)?this.a[a]:""};y.prototype.geil=y.prototype.c;var B=function(){var a=z,b=[];p(a.a,function(a){""!=a&&b.push(a)});return 0<a.b.length&&0<b.length?a.b.join(",")+","+b.join(","):a.b.join(",")+b.join(",")};var z,C="google_conversion_id google_conversion_format google_conversion_type google_conversion_order_id google_conversion_language google_conversion_value google_conversion_currency google_conversion_domain google_conversion_label google_conversion_color google_disable_viewthrough google_remarketing_only google_remarketing_for_search google_conversion_items google_custom_params google_conversion_date google_conversion_time google_conversion_js_version onload_callback opt_image_generator google_is_call google_conversion_page_url".split(" ");
function D(a){return null!=a?escape(a.toString()):""}function E(a){return null!=a?a.toString().substring(0,512):""}function F(a,b){var d=D(b);if(""!=d){var c=D(a);if(""!=c)return"&".concat(c,"=",d)}return""}function G(a){var b=typeof a;return null==a||"object"==b||"function"==b?null:String(a).replace(/,/g,"\\,").replace(/;/g,"\\;").replace(/=/g,"\\=")}
function H(a){var b;if((a=a.google_custom_params)&&"object"==typeof a&&"function"!=typeof a.join){var d=[];for(b in a)if(Object.prototype.hasOwnProperty.call(a,b)){var c=a[b];if(c&&"function"==typeof c.join){for(var e=[],g=0;g<c.length;++g){var m=G(c[g]);null!=m&&e.push(m)}c=0==e.length?null:e.join(",")}else c=G(c);(e=G(b))&&null!=c&&d.push(e+"="+c)}b=d.join(";")}else b="";return""==b?"":"&".concat("data=",encodeURIComponent(b))}
function I(a){return"number"!=typeof a&&"string"!=typeof a?"":D(a.toString())}function J(a){if(!a)return"";a=a.google_conversion_items;if(!a)return"";for(var b=[],d=0,c=a.length;d<c;d++){var e=a[d],g=[];e&&(g.push(I(e.value)),g.push(I(e.quantity)),g.push(I(e.item_id)),g.push(I(e.adwords_grouping)),g.push(I(e.sku)),b.push("("+g.join("*")+")"))}return 0<b.length?"&item="+b.join(""):""}
function K(a,b,d){var c=[];if(a){var e=a.screen;e&&(c.push(F("u_h",e.height)),c.push(F("u_w",e.width)),c.push(F("u_ah",e.availHeight)),c.push(F("u_aw",e.availWidth)),c.push(F("u_cd",e.colorDepth)));a.history&&c.push(F("u_his",a.history.length))}d&&"function"==typeof d.getTimezoneOffset&&c.push(F("u_tz",-d.getTimezoneOffset()));b&&("function"==typeof b.javaEnabled&&c.push(F("u_java",b.javaEnabled())),b.plugins&&c.push(F("u_nplug",b.plugins.length)),b.mimeTypes&&c.push(F("u_nmime",b.mimeTypes.length)));
return c.join("")}function L(a,b,d){var c="";if(b){var e;if(a.top==a)e=0;else{var g=a.location.ancestorOrigins;if(g)e=g[g.length-1]==a.location.origin?1:2;else{g=a.top;try{var m;if(m=!!g){var u;if(u=null!=g.location.href)n:{try{n(g.foo);u=!0;break n}catch(ga){}u=!1}m=u}e=m}catch(ha){e=!1}e=e?1:2}}m="";m=d?d:1==e?a.top.location.href:a.location.href;c+=F("frm",e);c+=F("url",E(m));c+=F("ref",E(b.referrer))}return c}
function M(a){return a&&a.location&&a.location.protocol&&"https:"==a.location.protocol.toString().toLowerCase()?"https:":"http:"}function N(a){return a.google_remarketing_only?"googleads.g.doubleclick.net":a.google_conversion_domain||"www.googleadservices.com"}
function O(a,b,d,c){var e="/?";"landing"==c.google_conversion_type&&(e="/extclk?");var e=M(a)+"//"+N(c)+"/pagead/"+[c.google_remarketing_only?"viewthroughconversion/":"conversion/",D(c.google_conversion_id),e,"random=",D(c.google_conversion_time)].join(""),g;r:{g=c.google_conversion_language;if(null!=g){g=g.toString();if(2==g.length){g=F("hl",g);break r}if(5==g.length){g=F("hl",g.substring(0,2))+F("gl",g.substring(3,5));break r}}g=""}a=[F("cv",c.google_conversion_js_version),F("fst",c.google_conversion_first_time),
F("num",c.google_conversion_snippets),F("fmt",c.google_conversion_format),F("value",c.google_conversion_value),F("currency_code",c.google_conversion_currency),F("label",c.google_conversion_label),F("oid",c.google_conversion_order_id),F("bg",c.google_conversion_color),g,F("guid","ON"),F("disvt",c.google_disable_viewthrough),F("is_call",c.google_is_call),F("eid",B()),J(c),K(a,b,c.google_conversion_date),H(c),L(a,d,c.google_conversion_page_url),c.google_remarketing_for_search&&!c.google_conversion_domain?
"&srr=n":""].join("");return e+a}function P(a){return{ar:1,bg:1,cs:1,da:1,de:1,el:1,en_AU:1,en_US:1,en_GB:1,es:1,et:1,fi:1,fr:1,hi:1,hr:1,hu:1,id:1,is:1,it:1,iw:1,ja:1,ko:1,lt:1,nl:1,no:1,pl:1,pt_BR:1,pt_PT:1,ro:1,ru:1,sk:1,sl:1,sr:1,sv:1,th:1,tl:1,tr:1,vi:1,zh_CN:1,zh_TW:1}[a]?a+".html":"en_US.html"}
function aa(){var a=Q,b=navigator,d=document,c=Q;3!=c.google_conversion_format||c.google_remarketing_only||c.google_conversion_domain||z&&A();var e=z?z.c(1):"",b=O(a,b,d,c),d=function(a,b,c){return'<img height="'+c+'" width="'+b+'" border="0" alt="" src="'+a+'" />'};return 0==c.google_conversion_format&&null==c.google_conversion_domain?'<a href="'+(M(a)+"//services.google.com/sitestats/"+P(c.google_conversion_language)+"?cid="+D(c.google_conversion_id))+'" target="_blank">'+d(b,135,27)+"</a>":1<c.google_conversion_snippets||
3==c.google_conversion_format?"317150501"==e||"317150502"==e||"317150503"==e||"317150504"==e||"317150505"==e?d(b,1,1)+('<script src="'+b.replace(/(&|\?)fmt=3(&|$)/,"$1fmt=4&adtest=on$2")+'">\x3c/script>'):d(b,1,1):'<iframe name="google_conversion_frame" title="Google conversion frame" width="'+(2==c.google_conversion_format?200:300)+'" height="'+(2==c.google_conversion_format?26:13)+'" src="'+b+'" frameborder="0" marginwidth="0" marginheight="0" vspace="0" hspace="0" allowtransparency="true" scrolling="no">'+
d(b.replace(/\?random=/,"?frame=0&random="),1,1)+"</iframe>"}function ba(){return new Image}function ca(){var a=R,b=S,d=ba;"function"===typeof a.opt_image_generator&&(d=a.opt_image_generator);a=d();b+=F("async","1");a.src=b;a.onload=function(){}};var Q=window;
if(Q)if(null!=/[\?&;]google_debug/.exec(document.URL)){var da=Q,T=document.getElementsByTagName("head")[0];T||(T=document.createElement("head"),document.getElementsByTagName("html")[0].insertBefore(T,document.getElementsByTagName("body")[0]));var U=document.createElement("script");U.src=M(window)+"//"+N(da)+"/pagead/conversion_debug_overlay.js";T.appendChild(U)}else{try{var V;var W=Q;"landing"==W.google_conversion_type||!W.google_conversion_id||W.google_remarketing_only&&W.google_disable_viewthrough?V=
!1:(W.google_conversion_date=new Date,W.google_conversion_time=W.google_conversion_date.getTime(),W.google_conversion_snippets="number"==typeof W.google_conversion_snippets&&0<W.google_conversion_snippets?W.google_conversion_snippets+1:1,"number"!=typeof W.google_conversion_first_time&&(W.google_conversion_first_time=W.google_conversion_time),W.google_conversion_js_version="7",0!=W.google_conversion_format&&1!=W.google_conversion_format&&2!=W.google_conversion_format&&3!=W.google_conversion_format&&
(W.google_conversion_format=1),z=new y(1),V=!0);if(V&&(document.write(aa()),Q.google_remarketing_for_search&&!Q.google_conversion_domain)){var R=Q,S,X=Q,ea=document,Y=R,Z;Z=M(X)+"//www.google.com/ads/user-lists/"+[D(Y.google_conversion_id),"/?random=",Math.floor(1E9*Math.random())].join("");S=Z+=[F("label",Y.google_conversion_label),F("fmt","3"),L(X,ea,Y.google_conversion_page_url)].join("");ca()}}catch(fa){}for(var ia=Q,$=0;$<C.length;$++)ia[C[$]]=null};})();
