//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace viviapi.ETAPI.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "12.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string netdemo_com_shengpay_cardpay_refund_RefundAPIExporterService {
            get {
                return ((string)(this["netdemo_com_shengpay_cardpay_refund_RefundAPIExporterService"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string netdemo_com_shengpay_cardpay_receive_ReceiveOrderAPIExplorterService {
            get {
                return ((string)(this["netdemo_com_shengpay_cardpay_receive_ReceiveOrderAPIExplorterService"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string netdemo_com_shengpay_cardpay_refundQuery_RefundQueryAPIExporterService {
            get {
                return ((string)(this["netdemo_com_shengpay_cardpay_refundQuery_RefundQueryAPIExporterService"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string netdemo_com_shengpay_cardpay_payment_PaymentAPIExporterService {
            get {
                return ((string)(this["netdemo_com_shengpay_cardpay_payment_PaymentAPIExporterService"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string netdemo_com_shengpay_cardpay_queryOrder_QueryOrderAPIExporterService {
            get {
                return ((string)(this["netdemo_com_shengpay_cardpay_queryOrder_QueryOrderAPIExporterService"]));
            }
        }
    }
}
